graph TD
A[fract2-development 755]:::directory --> B(LICENSE.md 644):::finished
A --> C(README.md 644):::finished
A --> D[config 755]:::directory
A --> E[distribution 755]:::directory
A --> F[docs 755]:::directory
A --> G(fract2-dist-packager.sh 755):::script
A --> H(index.php 644)
A --> I[packages 755]:::directory
A --> J[system 755]:::directory
A --> K[templates 755]:::directory

D --> D1(config.yaml 644)
D --> D2(database.yaml 644):::finished

E --> E1(fract2-setup.sh 755):::script

F --> F1(architecture_overview.md 644):::finished
F --> F2(database_design.md 644):::finished
F --> F3(fract2-file-structure.mermaid 644):::finished
F --> F4(fract2_file_structure.md 644):::finished
F --> F5(installation_process.md 644):::finished
F --> F6(package_structure.md 644):::finished
F --> F7(security_considerations.md 644):::finished

I --> I1[f2.atom.tar 755]:::directory
I --> I2[f2.content.tar 755]:::directory
I --> I3[f2.users.tar 755]:::directory

J --> J1[bootstrap 755]:::directory
J --> J2[core.tar 755]:::directory
J1 --> J1A(tarStreamWrapper.php 644):::finished

J2 --> J2A[database 755]:::directory
J2A --> J2A1[mariadb 755]:::directory
J2A --> J2A2[postgres 755]:::directory
J2A1 --> J2A1A(MariaDBConnection.php 644):::finished
J2A1 --> J2A1B(MariaDBQuery.php 644):::finished
J2A2 --> J2A2A(PostgresConnection.php 644):::finished
J2A2 --> J2A2B(PostgresQuery.php 644):::finished

K --> K1(index.twig 644)

classDef directory stroke:#FFFF00,stroke-width:4px;
classDef finished stroke:#90EE90,stroke-width:4px;
classDef script fill:#FFA07A,stroke:#333,stroke-width:2px;